projects/urls.py
from django.urls import path
from projects.views import (
    list_all_projects,
    list_my_projects,
    show_project,
    create_project,
    delete_project,
    edit_project_title_description,
    create_project_task,
    edit_project_task,
)

urlpatterns = [
    path("", list_all_projects, name="list_all_projects"),
    path("mine", list_my_projects, name="list_my_projects"),
    path("<int:id>/", show_project, name="show_project"),
    path(
        "create/",
        create_project,
        name="create_project",
    ),
    path(
        "<int:id>/edit/",
        edit_project_title_description,
        name="edit_project_title_description",
    ),
    path("<int:id>/delete/", delete_project, name="delete_project"),
    path(
        "<int:id>/create_task/",
        create_project_task,
        name="create_project_task",
    ),
    path(
        "task/<int:id>/edit/",
        edit_project_task,
        name="edit_project_task",
    ),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    create_my_task,
    show_my_tasks,
    edit_my_task,
)

urlpatterns = [
    path("mine/create/", create_my_task, name="create_my_task"),
    path("mine/", show_my_tasks, name="show_my_tasks"),
    path("<int:id>/edit", edit_my_task, name="edit_my_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def redirect_to_project_list(request):
    return redirect("list_all_projects")


urlpatterns = [
    path("", redirect_to_project_list, name="home"),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models
from django.conf import settings


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="projects",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from projects.models import Project
from django.conf import settings


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project,
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="tasks",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

projects/forms.py
from django import forms
from projects.models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "name",
            "description",
            "owner",
        ]

projects/views.py
from django.http import QueryDict
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from projects.models import Project
from projects.forms import ProjectForm
from tasks.forms import TaskEditForm, TaskForm
from tasks.models import Task
from projects.filters import ProjectFilterByOnwer


@login_required
def list_all_projects(request):
    project_filter = ProjectFilterByOnwer(
        request.GET, queryset=Project.objects.all()
    )
    context = {
        "filter_form": project_filter.form,
        "projects": project_filter.qs,
    }
    return render(request, "projects/list_all_projects.html", context)


@login_required
def list_my_projects(request):
    projects = Project.objects.filter(owner=request.user)
    context = {
        "projects": projects,
    }
    return render(request, "projects/list_projects.html", context)


@login_required
def show_project(request, id):
    project = get_object_or_404(Project, id=id)
    context = {
        "project": project,
    }
    if request.method == "GET":
        return render(request, "projects/show_project.html", context)
    elif request.method == "PUT":
        data = QueryDict(request.body).dict()
        form = ProjectForm(data, instance=project)
        if form.is_valid():
            form.save()
            return render(
                request,
                "projects/partials/project_title_description.html",
                context,
            )
    else:
        context = {
            "project_form": form,
        }
        return render(
            request,
            "projects/partials/edit_project_title_description.html",
            context,
        )


@login_required
def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(False)
            project.owner = project.owner
            project.save()
            return redirect("show_project", id=project.id)
    else:
        form = ProjectForm()
    context = {
        "project_form": form,
    }
    return render(request, "projects/create_project.html", context)


@login_required
def edit_project_title_description(request, id):
    project = get_object_or_404(Project, id=id)
    form = ProjectForm(instance=project)
    context = {
        "project_form": form,
        "project": project,
    }
    return render(
        request,
        "projects/partials/edit_project_title_description.html",
        context,
    )


@login_required
def delete_project(request, id):
    project = get_object_or_404(Project, id=id)
    if request.method == "POST":
        project.delete()
        return redirect("home")
    return render(request, "projects/delete_project.html")


@login_required
def create_project_task(request, id):
    project = get_object_or_404(Project, id=id)
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(False)
            task.owner = task.owner
            task.save()
            return redirect("show_project", id=task.project.id)
    else:
        form = TaskForm()
        form.fields["project"].queryset = Project.objects.filter(id=project.id)
    context = {
        "task_form": form,
    }
    return render(request, "projects/create_project_task.html", context)


@login_required
def edit_project_task(request, id):
    task = get_object_or_404(Task, id=id)
    if request.method == "POST":
        form = TaskEditForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save()
            return redirect("show_project", id=task.project.id)
    else:
        form = TaskEditForm(instance=task)
        form.fields["project"].queryset = Project.objects.filter(
            id=task.project.id
        )
    context = {
        "task_form": form,
        "task": task,
    }
    return render(request, "projects/edit_task.html", context)

projects/templates/projects/create_project.html
{% extends "base.html" %}

{% block title %}
    Create a new project
{% endblock title %}
{% block content %}
    <main>
        <div class="project-form">
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ project_form.as_p }}
                <input type="submit" value="Create" />
                <a href="javascript:window.history.back()">Cancel</a>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/create_project_task.html
{% extends "base.html" %}

{% block title %}
    Create a new task
{% endblock title %}
{% block content %}
    <main>
        <div class="task-form">
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                {{ task_form.as_p }}
                <script>
                    $(function () {
                        $("#id_due_date").datepicker();
                        $("#id_start_date").datepicker();
                    });
                </script>
                <input type="submit" value="Create" />
                <a href="javascript:window.history.back()">Cancel</a>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/delete_project.html
{% extends "base.html" %}

{% block title %}
    Delete Project
{% endblock title %}
{% block content %}
    <h1>Delete confirmation</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="javascript:window.history.back()">Cancel</a>
    </form>
{% endblock content %}

projects/templates/projects/edit_task.html
{% extends "base.html" %}

{% block title %}
    Edit Task
{% endblock title %}
{% block content %}
    <main>
        <div class="task-form">
            <h1>Edit Task</h1>
            <form method="post">
                {% csrf_token %}
                {{ task_form.as_p }}
                <input type="submit" value="Save" />
                <a href="{% url 'show_project' task.project.id %}">Cancel</a>
                <script>
      $(function () {
          $("#id_due_date").datepicker();
          $("#id_start_date").datepicker();
      });
                </script>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list_all_projects.html
{% extends "base.html" %}

{% block title %}
    All Projects
{% endblock title %}
{% block content %}
    <main>
        <div class="project-form project-list">
            <h1>All Projects</h1>
            <div>
                <a href="{% url 'create_project' %}">Create a new project</a>
            </div>
            {% if projects|length == 0 %}
                <div>You are not assigned to any projects.</div>
            {% else %}
                <div>
                    <h3>Filter projects by owner</h3>
                    <form method="get" action="{% url 'list_all_projects' %}">
                        {% csrf_token %}
                        {{ filter_form.as_p }}
                        <input type="submit" value="Submit">
                    </form>
                </div>
                <table>
                    <thead>
                        <tr>
                            <th>Project</th>
                            <th>Owner</th>
                            <th>Number of Tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td>
                                    <a href="{% url 'show_project' project.id %}">{{ project.name }}</a>
                                </td>
                                <td>{{ project.owner }}</td>
                                <td>{{ project.tasks.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list_projects.html
{% extends "base.html" %}

{% block title %}
    My Projects
{% endblock title %}
{% block content %}
    <main>
        <div class="project-form project-list">
            <h1>My Projects</h1>
            <div>
                <a href="{% url 'create_project' %}">Create a new project</a>
            </div>
            {% if projects|length == 0 %}
                <p>You are not assigned to any projects.</p>
            {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Project Name</th>
                            <th>Number of Tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td>
                                    <a href="{% url 'show_project' project.id %}">{{ project.name }}</a>
                                </td>
                                <td>{{ project.tasks.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/show_project.html
{% extends "base.html" %}

{% block title %}
    My Projects | {{ project.name }}
{% endblock title %}
{% block content %}
    <main>
        <div class="project-form project-detail">
            <div id="project_title_description">
                {% include "projects/partials/project_title_description.html" %}

            </div>
            <div>
                <a href="{% url 'delete_project' project.id %}">Delete project</a>
            </div>
            <h2>Tasks</h2>
            <a href="{% url 'create_project_task' project.id %}">Create a new task</a>
            {% if project.tasks.all|length == 0 %}
                <div>This project has no tasks</div>
            {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Task</th>
                            <th>Owner</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.owner }}</td>
                                <td>{{ task.start_date|date:"M n, Y" }}</td>
                                <td>{{ task.due_date|date:"M n, Y" }}</td>
                                <td>{{ task.is_completed|yesno:"Yes,No" }}</td>
                                <td>
                                    <a href="{% url 'edit_project_task' task.id %}">
                                        <button>Edit</button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}